# Generated by Django 4.0.6 on 2022-08-02 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserTop5',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=200)),
                ('division', models.CharField(max_length=200)),
                ('points', models.IntegerField(default=0)),
            ],
        ),
    ]
