# Generated by Django 4.0.6 on 2022-08-15 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalMeeting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
